### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by zyxcambridge** [Nutlope/notesGPT#13]
![image](https://github.com/Nutlope/notesGPT/assets/1818981/884fdf0b-b98f-4c0e-b0b0-4e796dc533c8)
(base) zhangyixin@zhangyixin notesGPT % 
(base) zhangyixin@zhangyixin notesGPT % 
(base) zhangyixin@zhangyixin notesGPT % 
(base) zhangyixin@zhangyixin notesGPT % npm install
(##################) ⠴ reify:convex: http fetch GET 200 https://registry.npmjs.org/convex/-/convex-1.9.0.tgz 39708ms (cache miss)
(##################) ⠴ reify:convex: http fetch GET 200 https://registry.npmjs.org/convex/-/convex-1.9.0.tgz 39708ms (cache miss)
(##################) ⠴ reify:convex: http fetch GET 200 https://registry.npmjs.org/convex/-/convex-1.9.0.tgz 39708ms (cache miss)

added 514 packages, and audited 515 packages in 3m

127 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
(base) zhangyixin@zhangyixin notesGPT % 
(base) zhangyixin@zhangyixin notesGPT % 
(base) zhangyixin@zhangyixin notesGPT % 
(base) zhangyixin@zhangyixin notesGPT % npm run dev

> notes-gpt@1.0.0 predev
> convex dev --until-success

Welcome to developing with Convex, let's get you logged in.
? Device name: 张益新’s MacBook Pro
Visit https://auth.convex.dev/activate?user_code=HLKX-DQTR to finish logging in.
You should see the following code which expires in 15 minutes: HLKX-DQTR
? Open the browser? Yes
✔ Saved credentials to ~/.convex/config.json
? Project name: notesGPT
✔ Created project notesgpt-a228a, manage it at https://dashboard.convex.dev/t/zyxcambridge/notesgpt-a228a
not overwriting README.md
not overwriting tsconfig.json
✔ Provisioned a dev deployment and saved its:
    name as CONVEX_DEPLOYMENT to .env.local
    URL as NEXT_PUBLIC_CONVEX_URL to .env.local

Write your Convex functions in convex/
Give us feedback at https://convex.dev/community or support@convex.dev

✔ Schema validation complete.
✔ Added table indexes:
  [+] actionItems.by_noteId ["noteId","_creationTime"]
  [+] actionItems.by_userId ["userId","_creationTime"]
  [+] notes.by_userId ["userId","_creationTime"]
  [+] notes.by_embedding {"dimensions":768,"vectorField":"embedding","filterFields":["userId"]}
Analyzing and deploying source code...
✖ Go to https://dashboard.convex.dev/t/zyxcambridge/notesgpt-a228a/modest-ostrich-109/settings/environment-variables?var=CLERK_ISSUER_URL to setup your environment variable.
Hit an error while pushing:
Environment variable CLERK_ISSUER_URL is used in auth config file but its value was not set
    at <anonymous> (../convex/auth.config.js:5:21)

✔ Schema validation complete.
Analyzing and deploying source code...
✖ Go to https://dashboard.convex.dev/t/zyxcambridge/notesgpt-a228a/modest-ostrich-109/settings/environment-variables?var=CLERK_ISSUER_URL to setup your environment variable.
Hit an error while pushing:
Environment variable CLERK_ISSUER_URL is used in auth config file but its value was not set
    at <anonymous> (../convex/auth.config.js:5:21)

⠋ Preparing Convex functions...
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
TypeError: Cannot read properties of undefined (reading 'numSubscribers')
    at LocalSyncState.removeSubscriber (/Users/zhangyixin/Desktop/notesGPT/node_modules/convex/dist/cli.bundle.cjs:275177:20)
    at unsubscribe (/Users/zhangyixin/Desktop/notesGPT/node_modules/convex/dist/cli.bundle.cjs:275033:33)
    at unsubscribe (/Users/zhangyixin/Desktop/notesGPT/node_modules/convex/dist/cli.bundle.cjs:276516:31)
    at stopWatching (/Users/zhangyixin/Desktop/notesGPT/node_modules/convex/dist/cli.bundle.cjs:276828:5)
⠹ Preparing Convex functions...
^C
(base) zhangyixin@zhangyixin notesGPT % 
(base) zhangyixin@zhangyixin notesGPT % 
(base) zhangyixin@zhangyixin notesGPT % npm run dev

> notes-gpt@1.0.0 predev
> convex dev --until-success

✔ Schema validation complete.
Analyzing and deploying source code...
✖ Go to https://dashboard.convex.dev/t/zyxcambridge/notesgpt-a228a/modest-ostrich-109/settings/environment-variables?var=CLERK_ISSUER_URL to setup your environment variable.
Hit an error while pushing:
Environment variable CLERK_ISSUER_URL is used in auth config file but its value was not set
    at <anonymous> (../convex/auth.config.js:5:21)

✔ Schema validation complete.
Analyzing and deploying source code...
✔ 22:23:27 Convex functions ready! (6.84s)

> notes-gpt@1.0.0 dev
> npm-run-all --parallel dev:backend dev:frontend

> notes-gpt@1.0.0 dev:frontend
> next dev

> notes-gpt@1.0.0 dev:backend
> convex dev

 ⚠ Port 3000 is in use, trying 3001 instead.
   ▲ Next.js 14.0.4
   - Local:        http://localhost:3001
   - Environments: .env.local

⠙ Checking for index or schema changes...
✔ 22:23:36 Convex functions ready! (5.78s)
 ○ Compiling /middleware ...
 ✓ Compiled /middleware in 904ms (283 modules)
<w> [webpack.cache.PackFileCacheStrategy] Serializing big strings (101kiB) impacts deserialization performance (consider using Buffer instead and decode when needed)
 ✓ Compiled /favicon.ico in 127ms (44 modules)
 ○ Compiling / ...
 ✓ Compiled / in 2.2s (990 modules)
 ⚠ The "images.domains" configuration is deprecated. Please use "images.remotePatterns" configuration instead.
 ✓ Compiled in 270ms (467 modules)
INFO: Clerk: The request to /dashboard is being redirected because there is no signed-in user, and the path is not included in `ignoredRoutes` or `publicRoutes`. To prevent this behavior, choose one of:

1. To make the route accessible to both signed in and signed out users, add "/dashboard" to the `publicRoutes` array passed to authMiddleware
2. To prevent Clerk authentication from running at all, pass `ignoredRoutes: ["/((?!api|trpc))(_next.*|.+\.[\w]+$)", "/dashboard"]` to authMiddleware
3. Pass a custom `afterAuth` to authMiddleware, and replace Clerk's default behavior of redirecting unless a route is included in publicRoutes

For additional information about middleware, please visit https://clerk.com/docs/nextjs/middleware
(This log only appears in development mode, or if `debug: true` is passed to authMiddleware)
INFO: Clerk: The request to /dashboard is being redirected because there is no signed-in user, and the path is not included in `ignoredRoutes` or `publicRoutes`. To prevent this behavior, choose one of:

1. To make the route accessible to both signed in and signed out users, add "/dashboard" to the `publicRoutes` array passed to authMiddleware
2. To prevent Clerk authentication from running at all, pass `ignoredRoutes: ["/((?!api|trpc))(_next.*|.+\.[\w]+$)", "/dashboard"]` to authMiddleware
3. Pass a custom `afterAuth` to authMiddleware, and replace Clerk's default behavior of redirecting unless a route is included in publicRoutes

For additional information about middleware, please visit https://clerk.com/docs/nextjs/middleware
(This log only appears in development mode, or if `debug: true` is passed to authMiddleware)
INFO: Clerk: The request to /dashboard is being redirected because there is no signed-in user, and the path is not included in `ignoredRoutes` or `publicRoutes`. To prevent this behavior, choose one of:

1. To make the route accessible to both signed in and signed out users, add "/dashboard" to the `publicRoutes` array passed to authMiddleware
2. To prevent Clerk authentication from running at all, pass `ignoredRoutes: ["/((?!api|trpc))(_next.*|.+\.[\w]+$)", "/dashboard"]` to authMiddleware
3. Pass a custom `afterAuth` to authMiddleware, and replace Clerk's default behavior of redirecting unless a route is included in publicRoutes

For additional information about middleware, please visit https://clerk.com/docs/nextjs/middleware
(This log only appears in development mode, or if `debug: true` is passed to authMiddleware)
 ○ Compiling /dashboard ...
 ✓ Compiled /dashboard in 992ms (1253 modules)
 ⨯ node_modules/@clerk/backend/dist/esm/index.js (1330:18) @ SessionAPI.eval [as request]
 ⨯ Error: Not Found
    at async getAuthToken (./app/auth.ts:8:12)
    at async ServerDashboardHomePage (./app/dashboard/page.tsx:17:19)
null
 ⨯ node_modules/@clerk/backend/dist/esm/index.js (1330:18) @ SessionAPI.eval [as request]
 ⨯ Error: Not Found
    at async getAuthToken (./app/auth.ts:8:12)
    at async ServerDashboardHomePage (./app/dashboard/page.tsx:17:19)
digest: "2533320378"
null
 ✓ Compiled in 122ms (507 modules)
 ⚠ Fast Refresh had to perform a full reload due to a runtime error.
 ⨯ node_modules/@clerk/backend/dist/esm/index.js (1330:18) @ SessionAPI.eval [as request]
 ⨯ Error: Not Found
    at async getAuthToken (./app/auth.ts:8:12)
    at async ServerDashboardHomePage (./app/dashboard/page.tsx:17:19)
null
 ⨯ node_modules/@clerk/backend/dist/esm/index.js (1330:18) @ SessionAPI.eval [as request]
 ⨯ Error: Not Found
    at async getAuthToken (./app/auth.ts:8:12)
    at async ServerDashboardHomePage (./app/dashboard/page.tsx:17:19)
digest: "2533320378"
null
 ⨯ node_modules/@clerk/backend/dist/esm/index.js (1330:18) @ SessionAPI.eval [as request]
 ⨯ Error: Not Found
    at async getAuthToken (./app/auth.ts:8:12)
    at async ServerDashboardHomePage (./app/dashboard/page.tsx:17:19)
null
 ⨯ node_modules/@clerk/backend/dist/esm/index.js (1330:18) @ SessionAPI.eval [as request]
 ⨯ Error: Not Found
    at async getAuthToken (./app/auth.ts:8:12)
    at async ServerDashboardHomePage (./app/dashboard/page.tsx:17:19)
digest: "2533320378"
null
 ⨯ node_modules/@clerk/backend/dist/esm/index.js (1330:18) @ SessionAPI.eval [as request]
 ⨯ Error: Not Found
    at async getAuthToken (./app/auth.ts:8:12)
    at async ServerDashboardHomePage (./app/dashboard/page.tsx:17:19)
null

**Comment by zyxcambridge** [comment]
![image](https://github.com/Nutlope/notesGPT/assets/1818981/6181149a-17e2-4f5f-984c-243f5e78b9d7)
![image](https://github.com/Nutlope/notesGPT/assets/1818981/ce5332cd-984b-4e77-8be3-edc371de0f90)
![image](https://github.com/Nutlope/notesGPT/assets/1818981/4c4ba35f-a4c1-4044-8852-fe376a6df7da)

**Comment by Nutlope** [comment]
@zyxcambridge these issues were fixed in #15! Thanks for reporting
