### ISSUE TITLE
Application error

### ISSUE THREAD

**Issue by Behumanto** [Nutlope/notesGPT#14]
Hi, there are some issues, regarding going to a transcript, it gives an application error

**Comment by MrVelasquezz** [comment]
May be it will help developers to detect an error faster
Console error:  Error: currentUser() can only be used in a server environment.
Browser: Chrome 
Platform: Win 10

**Comment by Nutlope** [comment]
@Behumanto @MrVelasquezz these issues were fixed in #15!
