### ISSUE TITLE
Very laggy  in local host and enable to run 

### ISSUE THREAD

**Issue by Ali-Aljufairi** [Nutlope/notesGPT#17]
Hello, I find the idea intriguing and I'm interested in contributing to some features. 

However, I have followed the setups for  Deployting and followed them all but I found website very laggy and unable to even recorded a voice note so could 

MY PC :

i9900K
32 GB RAM

https://github.com/Nutlope/notesGPT/assets/85583841/8dfb9a77-369c-48fd-806f-3e61950d8bd5

I would love if could clarify  on what environments to deploy website on so we can test freely on some features

**Comment by Nutlope** [comment]
Hi @Ali-Aljufairi! Had some issues with some PRs I merged yesterday that were just fixed today so I'm sorry about that! Can you please pull the latest changes, run `npx convex deploy`, and try again?

**Comment by Ali-Aljufairi** [comment]
Yup, Thank it's work now I appreciate it 

By the way, are there any guidelines for contributing? 

I would  like to add some features that I want  to personally in the website

1. Exporting Action items to the Todo list app 
2. Dark mode    

We would love to help with this amazing project  if there are some features that no one is working on currently  
and not that of complex Task I could help on doing them
